import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  title: { fontSize: 20, marginBottom: 5, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 12, color: "#666", marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 20, marginBottom: 10 },
  kpiRow: { flexDirection: "row", marginBottom: 15, gap: 10 },
  kpiCard: { flex: 1, padding: 10, backgroundColor: "#f3f4f6", borderRadius: 4 },
  kpiLabel: { fontSize: 8, color: "#666" },
  kpiValue: { fontSize: 16, fontFamily: "Helvetica-Bold", marginTop: 2 },
  tableHeader: { flexDirection: "row", backgroundColor: "#f3f4f6", padding: 6, marginBottom: 2 },
  tableRow: { flexDirection: "row", padding: 6, borderBottomWidth: 0.5, borderBottomColor: "#e5e7eb" },
  cellCode: { width: 50, fontSize: 8, color: "#999" },
  cellName: { flex: 1, fontSize: 9 },
  cellNum: { width: 70, textAlign: "right", fontSize: 9 },
  cellNumBold: { width: 70, textAlign: "right", fontSize: 9, fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#999", textAlign: "center" },
});

function formatCurrency(value: number): string {
  if (value >= 1_000_000) return `$${(value / 1_000_000).toFixed(1)}M`;
  if (value >= 1_000) return `$${(value / 1_000).toFixed(0)}K`;
  return `$${value.toFixed(0)}`;
}

type AnalysisNode = {
  nodeCode: string;
  nodeName: string;
  level: number;
  effectiveLocation: string | null;
  fteAtNonPreferred: number;
  costAtNonPreferred: number;
  savings: number;
};

type Props = {
  projectName: string;
  date: string;
  totals: {
    totalFte: number;
    totalCurrentCost: number;
    totalFutureCost: number;
    totalSavings: number;
    fteAffected: number;
    responseRate: number;
  };
  topSavings: AnalysisNode[];
};

export function PdfReport({ projectName, date, totals, topSavings }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Activity Assessment Report</Text>
        <Text style={styles.subtitle}>
          {projectName} — {date}
        </Text>

        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <View style={styles.kpiRow}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Current Cost (Non-Preferred)</Text>
            <Text style={styles.kpiValue}>{formatCurrency(totals.totalCurrentCost)}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Future Cost (Shared Services)</Text>
            <Text style={styles.kpiValue}>{formatCurrency(totals.totalFutureCost)}</Text>
          </View>
          <View style={[styles.kpiCard, { backgroundColor: "#dcfce7" }]}>
            <Text style={styles.kpiLabel}>Potential Savings</Text>
            <Text style={[styles.kpiValue, { color: "#166534" }]}>
              {formatCurrency(totals.totalSavings)}
            </Text>
          </View>
        </View>
        <View style={styles.kpiRow}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Total FTEs Analyzed</Text>
            <Text style={styles.kpiValue}>{totals.totalFte.toFixed(1)}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>FTEs Affected</Text>
            <Text style={styles.kpiValue}>{totals.fteAffected.toFixed(1)}</Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Response Rate</Text>
            <Text style={styles.kpiValue}>{totals.responseRate}%</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Top 10 Savings Opportunities</Text>
        <View style={styles.tableHeader}>
          <Text style={styles.cellCode}>Code</Text>
          <Text style={styles.cellName}>Activity</Text>
          <Text style={styles.cellNum}>FTE Gap</Text>
          <Text style={styles.cellNum}>Cost Gap</Text>
          <Text style={styles.cellNumBold}>Savings</Text>
        </View>
        {topSavings.map((node, i) => (
          <View key={i} style={styles.tableRow}>
            <Text style={styles.cellCode}>{node.nodeCode}</Text>
            <Text style={styles.cellName}>{node.nodeName}</Text>
            <Text style={styles.cellNum}>{node.fteAtNonPreferred.toFixed(1)}</Text>
            <Text style={styles.cellNum}>{formatCurrency(node.costAtNonPreferred)}</Text>
            <Text style={styles.cellNumBold}>{formatCurrency(node.savings)}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by Activity Assessment Tool on {date}
        </Text>
      </Page>
    </Document>
  );
}
